### ISSUE TITLE
Question: bindfs

### ISSUE THREAD

**Issue by dersimn** [josepsanzcamp/root-ro#3]
Why is the `bindfs` needed?
https://github.com/josepsanzcamp/root-ro/blob/1637a2c4cdae0daa1c891572fe0d5eafdeb7e28b/etc/initramfs-tools/scripts/init-bottom/root-ro#L156

or what's the purpose behind having `/mnt/boot-ro` and `/mnt/boot-ro2`?

**Comment by josepsanzcamp** [comment]
Hi Simon.

The boot-ro2 exists as a trick to allow the mount using the overlayfs, if you try to mount a vfat using the overlayfs, it
will fails because it's not suported, and the only way that I was found when I do it was to use a temporary mount point using the bindfs, it's only as a trick to get the same feature for the boot and the root partitions, with this you can modify too the boot partition as the root using the overlayfs!!!

Josep.

--
Josep Sanz Campderrós
http://www.josepsanz.net
The SaltOS project
http://www.saltos.org
